
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - db:/var/lib/postgresql/data/
    ports: 
      - "5432:5432"

volumes:
  db:
    name: db 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/katarina-db
